<?php

namespace Database\Seeders;

use App\Models\Batch;
use App\Models\Category;
use App\Models\Medicine;
use App\Models\MedicineUnit;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    /**
     * Seed popular, high-volume medicines commonly dispensed and prescribed in Uganda.
     */
    public function run(): void
    {
        $categories = Category::all()->keyBy('name');
        $suppliers = Supplier::all()->keyBy('name');

        $defaultSupplier = $suppliers->first();
        $jmsSupplier = $suppliers->get('Joint Medical Store (JMS)') ?? $defaultSupplier;
        $nmsSupplier = $suppliers->get('National Medical Stores (NMS)') ?? $defaultSupplier;
        $abacusSupplier = $suppliers->get('Abacus Pharma (A) Ltd') ?? $defaultSupplier;
        $ciplaSupplier = $suppliers->get('Cipla Quality Chemical Industries Ltd') ?? $defaultSupplier;
        $reneSupplier = $suppliers->get('Rene Industries Ltd') ?? $defaultSupplier;
        $kpiSupplier = $suppliers->get('Kampala Pharmaceutical Industries Ltd (KPI)') ?? $defaultSupplier;
        $surgipharmSupplier = $suppliers->get('Surgipharm (U) Ltd') ?? $defaultSupplier;
        $astraSupplier = $suppliers->get('AstraPharma Wholesale Ltd') ?? $defaultSupplier;

        $medicinesData = [
            // ── ANTIMALARIALS ──────────────────────────────────────────────────────────
            [
                'name' => 'Coartem 80/480mg Tablets (6x1)',
                'generic_name' => 'Artemether 80mg + Lumefantrine 480mg',
                'category_name' => 'Antimalarials & Antiparasitics',
                'manufacturer' => 'Novartis / Cipla QCIL',
                'base_unit' => 'Tablet',
                'description' => 'First-line ACT for uncomplicated falciparum malaria in adults. 6 tablets per treatment course.',
                'reorder_level' => 30,
                'requires_prescription' => true,
                'supplier_id' => $ciplaSupplier->id ?? null,
                'batch_number' => 'CTM80-' . date('y') . '041',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+22 months')),
                'purchase_price' => 1350.00,  // ~8,100 UGX per strip
                'selling_price' => 2000.00,   // 12,000 UGX per strip (6 tabs)
                'initial_stock' => 360,       // 60 strips (10 boxes of 6 strips)
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 6, 'selling_price' => 12000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 36, 'selling_price' => 70000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Coartem 20/120mg Tablets (6x4)',
                'generic_name' => 'Artemether 20mg + Lumefantrine 120mg',
                'category_name' => 'Antimalarials & Antiparasitics',
                'manufacturer' => 'Novartis / Cipla QCIL',
                'base_unit' => 'Tablet',
                'description' => 'Paediatric & general Artemether-Lumefantrine for treatment of acute uncomplicated malaria.',
                'reorder_level' => 50,
                'requires_prescription' => true,
                'supplier_id' => $ciplaSupplier->id ?? null,
                'batch_number' => 'CTM20-' . date('y') . '108',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+24 months')),
                'purchase_price' => 350.00,
                'selling_price' => 500.00,   // 12,000 UGX per strip of 24
                'initial_stock' => 480,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 24, 'selling_price' => 12000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 240, 'selling_price' => 115000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Lonart Forte Tablets (4x6)',
                'generic_name' => 'Artemether 80mg + Lumefantrine 480mg',
                'category_name' => 'Antimalarials & Antiparasitics',
                'manufacturer' => 'Bliss GVS Pharma / Abacus Pharma',
                'base_unit' => 'Tablet',
                'description' => 'Fast-acting Artemether + Lumefantrine fixed dose combination tablets.',
                'reorder_level' => 24,
                'requires_prescription' => true,
                'supplier_id' => $abacusSupplier->id ?? null,
                'batch_number' => 'LNT-' . date('y') . '302',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+26 months')),
                'purchase_price' => 1400.00,
                'selling_price' => 2100.00,
                'initial_stock' => 180,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 6, 'selling_price' => 12500.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 36, 'selling_price' => 72000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Duo-Cotecxin Tablets',
                'generic_name' => 'Dihydroartemisinin 40mg + Piperaquine Phosphate 320mg',
                'category_name' => 'Antimalarials & Antiparasitics',
                'manufacturer' => 'Zhejiang Holley / Surgipharm',
                'base_unit' => 'Tablet',
                'description' => 'Dihydroartemisinin-Piperaquine (DHA-PPQ) alternative first-line ACT.',
                'reorder_level' => 20,
                'requires_prescription' => true,
                'supplier_id' => $surgipharmSupplier->id ?? null,
                'batch_number' => 'DCTX-' . date('y') . '019',
                'mfg_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+20 months')),
                'purchase_price' => 1800.00,
                'selling_price' => 2750.00,
                'initial_stock' => 160,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 8, 'selling_price' => 22000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 48, 'selling_price' => 128000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Artesunate Injection 60mg',
                'generic_name' => 'Artesunate 60mg (with Sodium Bicarbonate & Saline Ampoules)',
                'category_name' => 'Antimalarials & Antiparasitics',
                'manufacturer' => 'Guilin Pharmaceutical / JMS',
                'base_unit' => 'Vial',
                'description' => 'WHO recommended first-line parenteral therapy for severe and complicated malaria.',
                'reorder_level' => 15,
                'requires_prescription' => true,
                'supplier_id' => $jmsSupplier->id ?? null,
                'batch_number' => 'ART60-' . date('y') . '550',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+28 months')),
                'purchase_price' => 6500.00,
                'selling_price' => 9500.00,
                'initial_stock' => 50,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 10, 'selling_price' => 90000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Quinine Sulphate 300mg Tablets',
                'generic_name' => 'Quinine Sulphate 300mg',
                'category_name' => 'Antimalarials & Antiparasitics',
                'manufacturer' => 'Rene Industries Ltd',
                'base_unit' => 'Tablet',
                'description' => 'Cinchona alkaloid antimalarial for severe malaria and second-line therapy.',
                'reorder_level' => 100,
                'requires_prescription' => true,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'QN300-' . date('y') . '112',
                'mfg_date' => date('Y-m-d', strtotime('-6 months')),
                'expiry_date' => date('Y-m-d', strtotime('+30 months')),
                'purchase_price' => 150.00,
                'selling_price' => 300.00,
                'initial_stock' => 1000,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 3000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 1000, 'selling_price' => 260000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── PAIN RELIEF & ANALGESICS ────────────────────────────────────────────────
            [
                'name' => 'Panadol Extra Tablets',
                'generic_name' => 'Paracetamol 500mg + Caffeine 65mg',
                'category_name' => 'Pain Relief & Analgesics',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'base_unit' => 'Tablet',
                'description' => 'Fast-acting relief from tough headaches, toothaches, body pains, and fever.',
                'reorder_level' => 100,
                'requires_prescription' => false,
                'supplier_id' => $astraSupplier->id ?? null,
                'batch_number' => 'PDX-' . date('y') . '901',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+33 months')),
                'purchase_price' => 200.00,
                'selling_price' => 300.00,
                'initial_stock' => 1200,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 3000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 28000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Action Tablets (Paracetamol + Aspirin + Caffeine)',
                'generic_name' => 'Paracetamol 400mg + Aspirin 100mg + Caffeine 50mg',
                'category_name' => 'Pain Relief & Analgesics',
                'manufacturer' => 'Elys Chemical Industries / AstraPharma',
                'base_unit' => 'Tablet',
                'description' => 'Popular fast triple-action remedy for severe headaches and body aches.',
                'reorder_level' => 100,
                'requires_prescription' => false,
                'supplier_id' => $astraSupplier->id ?? null,
                'batch_number' => 'ACT-' . date('y') . '442',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+34 months')),
                'purchase_price' => 180.00,
                'selling_price' => 300.00,
                'initial_stock' => 800,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 3000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 200, 'selling_price' => 54000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Hedex Extra Tablets',
                'generic_name' => 'Paracetamol 500mg + Caffeine 65mg',
                'category_name' => 'Pain Relief & Analgesics',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'base_unit' => 'Tablet',
                'description' => 'Targeted extra strength formulation for rapid headache relief.',
                'reorder_level' => 80,
                'requires_prescription' => false,
                'supplier_id' => $astraSupplier->id ?? null,
                'batch_number' => 'HDX-' . date('y') . '219',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+32 months')),
                'purchase_price' => 200.00,
                'selling_price' => 300.00,
                'initial_stock' => 600,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 3000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 28000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Ibuprofen 400mg Tablets',
                'generic_name' => 'Ibuprofen 400mg',
                'category_name' => 'Pain Relief & Analgesics',
                'manufacturer' => 'Kampala Pharmaceutical Industries (KPI)',
                'base_unit' => 'Tablet',
                'description' => 'NSAID for relief of mild to moderate pain, inflammation, swelling, and arthritis.',
                'reorder_level' => 100,
                'requires_prescription' => false,
                'supplier_id' => $kpiSupplier->id ?? null,
                'batch_number' => 'IBU400-' . date('y') . '710',
                'mfg_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+31 months')),
                'purchase_price' => 100.00,
                'selling_price' => 200.00,
                'initial_stock' => 1500,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 2000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 1000, 'selling_price' => 180000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Diclofenac Sodium 50mg Tablets',
                'generic_name' => 'Diclofenac Sodium 50mg',
                'category_name' => 'Pain Relief & Analgesics',
                'manufacturer' => 'Rene Industries Ltd',
                'base_unit' => 'Tablet',
                'description' => 'Anti-inflammatory agent for joint pain, post-traumatic pain, and musculoskeletal disorders.',
                'reorder_level' => 60,
                'requires_prescription' => true,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'DIC50-' . date('y') . '334',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+33 months')),
                'purchase_price' => 120.00,
                'selling_price' => 250.00,
                'initial_stock' => 600,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 2500.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 22000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Tramadol Hydrochloride 50mg Capsules',
                'generic_name' => 'Tramadol HCl 50mg',
                'category_name' => 'Pain Relief & Analgesics',
                'manufacturer' => 'Cipla QCIL / Medisell',
                'base_unit' => 'Capsule',
                'description' => 'Centrally acting opioid analgesic for moderate to moderately severe acute and chronic pain.',
                'reorder_level' => 30,
                'requires_prescription' => true,
                'supplier_id' => $ciplaSupplier->id ?? null,
                'batch_number' => 'TRM50-' . date('y') . '088',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+34 months')),
                'purchase_price' => 350.00,
                'selling_price' => 600.00,
                'initial_stock' => 300,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 6000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 55000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── ANTIBIOTICS & ANTIMICROBIALS ──────────────────────────────────────────
            [
                'name' => 'Amoxicillin 500mg Capsules',
                'generic_name' => 'Amoxicillin Trihydrate 500mg',
                'category_name' => 'Antibiotics & Antimicrobials',
                'manufacturer' => 'Kampala Pharmaceutical Industries (KPI)',
                'base_unit' => 'Capsule',
                'description' => 'Broad-spectrum aminopenicillin for ear, throat, chest, and urinary tract infections.',
                'reorder_level' => 100,
                'requires_prescription' => true,
                'supplier_id' => $kpiSupplier->id ?? null,
                'batch_number' => 'AMX500-' . date('y') . '601',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+26 months')),
                'purchase_price' => 250.00,
                'selling_price' => 500.00,
                'initial_stock' => 1000,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 5000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 45000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Augmentin 625mg Tablets (Clavamox / Co-amoxiclav)',
                'generic_name' => 'Amoxicillin 500mg + Clavulanic Acid 125mg',
                'category_name' => 'Antibiotics & Antimicrobials',
                'manufacturer' => 'GlaxoSmithKline (GSK) / Cipla QCIL',
                'base_unit' => 'Tablet',
                'description' => 'Potentiated beta-lactamase resistant penicillin for severe and resistant bacterial infections.',
                'reorder_level' => 30,
                'requires_prescription' => true,
                'supplier_id' => $ciplaSupplier->id ?? null,
                'batch_number' => 'AUG625-' . date('y') . '412',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+22 months')),
                'purchase_price' => 1600.00,
                'selling_price' => 2500.00,
                'initial_stock' => 280,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 7, 'selling_price' => 17500.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 14, 'selling_price' => 34000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Ciprofloxacin 500mg Tablets (Cipro)',
                'generic_name' => 'Ciprofloxacin Hydrochloride 500mg',
                'category_name' => 'Antibiotics & Antimicrobials',
                'manufacturer' => 'Abacus Pharma / Rene Industries',
                'base_unit' => 'Tablet',
                'description' => 'Fluoroquinolone antibiotic for UTIs, typhoid fever, enteric infections, and gonorrhoea.',
                'reorder_level' => 60,
                'requires_prescription' => true,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'CIP500-' . date('y') . '822',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+27 months')),
                'purchase_price' => 250.00,
                'selling_price' => 500.00,
                'initial_stock' => 600,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 5000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 46000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Azithromycin 500mg Tablets (Azimax)',
                'generic_name' => 'Azithromycin Dihydrate 500mg',
                'category_name' => 'Antibiotics & Antimicrobials',
                'manufacturer' => 'Cipla QCIL / Surgipharm',
                'base_unit' => 'Tablet',
                'description' => 'Macrolide antibiotic 3-day course for respiratory tract infections, STIs, and skin infections.',
                'reorder_level' => 25,
                'requires_prescription' => true,
                'supplier_id' => $ciplaSupplier->id ?? null,
                'batch_number' => 'AZM500-' . date('y') . '119',
                'mfg_date' => date('Y-m-d', strtotime('-1 months')),
                'expiry_date' => date('Y-m-d', strtotime('+29 months')),
                'purchase_price' => 2000.00,
                'selling_price' => 3500.00,
                'initial_stock' => 150,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 3, 'selling_price' => 10500.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 18, 'selling_price' => 60000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Metronidazole 400mg Tablets (Flagyl)',
                'generic_name' => 'Metronidazole 400mg',
                'category_name' => 'Antibiotics & Antimicrobials',
                'manufacturer' => 'Rene Industries Ltd',
                'base_unit' => 'Tablet',
                'description' => 'Antiprotozoal and anaerobic antibiotic for amoebiasis, giardiasis, and pelvic infections.',
                'reorder_level' => 100,
                'requires_prescription' => true,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'MTZ400-' . date('y') . '031',
                'mfg_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+31 months')),
                'purchase_price' => 100.00,
                'selling_price' => 200.00,
                'initial_stock' => 1000,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 2000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 1000, 'selling_price' => 170000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Ampiclox 500mg Capsules',
                'generic_name' => 'Ampicillin 250mg + Cloxacillin 250mg',
                'category_name' => 'Antibiotics & Antimicrobials',
                'manufacturer' => 'Kampala Pharmaceutical Industries (KPI)',
                'base_unit' => 'Capsule',
                'description' => 'Combined penicillin therapy for mixed gram-positive and gram-negative bacterial infections.',
                'reorder_level' => 50,
                'requires_prescription' => true,
                'supplier_id' => $kpiSupplier->id ?? null,
                'batch_number' => 'APX500-' . date('y') . '508',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+26 months')),
                'purchase_price' => 300.00,
                'selling_price' => 500.00,
                'initial_stock' => 500,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 5000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 48000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Ceftriaxone 1g Injection',
                'generic_name' => 'Ceftriaxone Sodium 1g (Vial + Solvent)',
                'category_name' => 'Antibiotics & Antimicrobials',
                'manufacturer' => 'Abacus Parenteral Drugs (APDL)',
                'base_unit' => 'Vial',
                'description' => 'Third-generation cephalosporin for severe hospital/clinic infections, meningitis, and sepsis.',
                'reorder_level' => 20,
                'requires_prescription' => true,
                'supplier_id' => $abacusSupplier->id ?? null,
                'batch_number' => 'CTX1G-' . date('y') . '922',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+28 months')),
                'purchase_price' => 3500.00,
                'selling_price' => 6000.00,
                'initial_stock' => 60,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 10, 'selling_price' => 57000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── COUGH, COLD, FLU & RESPIRATORY ──────────────────────────────────────────
            [
                'name' => 'Ventolin Inhaler 100mcg (Salbutamol)',
                'generic_name' => 'Salbutamol Sulphate 100mcg/actuation (200 doses)',
                'category_name' => 'Cough, Cold, Flu & Respiratory',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'base_unit' => 'Inhaler',
                'description' => 'Fast-acting bronchodilator for rapid relief of asthma attacks and bronchospasm.',
                'reorder_level' => 15,
                'requires_prescription' => true,
                'supplier_id' => $astraSupplier->id ?? null,
                'batch_number' => 'VNT100-' . date('y') . '007',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+27 months')),
                'purchase_price' => 16000.00,
                'selling_price' => 22000.00,
                'initial_stock' => 40,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 10, 'selling_price' => 210000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Ascoril Expectorant Syrup (100ml)',
                'generic_name' => 'Salbutamol + Bromhexine HCl + Guaiphenesin + Menthol',
                'category_name' => 'Cough, Cold, Flu & Respiratory',
                'manufacturer' => 'Glenmark Pharmaceuticals / AstraPharma',
                'base_unit' => 'Bottle',
                'description' => 'Mucolytic expectorant and bronchodilator syrup for productive cough with bronchospasm.',
                'reorder_level' => 20,
                'requires_prescription' => false,
                'supplier_id' => $astraSupplier->id ?? null,
                'batch_number' => 'ASC100-' . date('y') . '140',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+26 months')),
                'purchase_price' => 8500.00,
                'selling_price' => 12500.00,
                'initial_stock' => 50,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 24, 'selling_price' => 285000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Benylin 4Flu Liquid (100ml)',
                'generic_name' => 'Diphenhydramine + Pseudoephedrine + Paracetamol',
                'category_name' => 'Cough, Cold, Flu & Respiratory',
                'manufacturer' => 'Johnson & Johnson / Surgipharm',
                'base_unit' => 'Bottle',
                'description' => 'Comprehensive 4-in-1 relief from fever, nasal congestion, body aches, and cough.',
                'reorder_level' => 15,
                'requires_prescription' => false,
                'supplier_id' => $surgipharmSupplier->id ?? null,
                'batch_number' => 'BNY4F-' . date('y') . '331',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+24 months')),
                'purchase_price' => 12000.00,
                'selling_price' => 17000.00,
                'initial_stock' => 35,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 20, 'selling_price' => 325000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Cold Cap Capsules (4x10)',
                'generic_name' => 'Paracetamol + Chlorpheniramine + Phenylephrine + Caffeine',
                'category_name' => 'Cough, Cold, Flu & Respiratory',
                'manufacturer' => 'Elys Chemical / Rene Industries',
                'base_unit' => 'Capsule',
                'description' => 'Fast-acting multi-symptom cold & flu capsules for headache, running nose, and fever.',
                'reorder_level' => 40,
                'requires_prescription' => false,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'CCAP-' . date('y') . '677',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+31 months')),
                'purchase_price' => 400.00,
                'selling_price' => 750.00,
                'initial_stock' => 400,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 4, 'selling_price' => 3000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 40, 'selling_price' => 28000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── ALLERGY & ANTIHISTAMINES ────────────────────────────────────────────────
            [
                'name' => 'Cetirizine 10mg Tablets',
                'generic_name' => 'Cetirizine Dihydrochloride 10mg',
                'category_name' => 'Allergy & Antihistamines',
                'manufacturer' => 'Rene Industries Ltd',
                'base_unit' => 'Tablet',
                'description' => 'Non-sedating second generation antihistamine for allergic rhinitis, hives, and pruritus.',
                'reorder_level' => 60,
                'requires_prescription' => false,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'CTZ10-' . date('y') . '209',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+32 months')),
                'purchase_price' => 150.00,
                'selling_price' => 300.00,
                'initial_stock' => 500,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 3000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 26000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Piriton 4mg Tablets (Chlorpheniramine)',
                'generic_name' => 'Chlorpheniramine Maleate 4mg',
                'category_name' => 'Allergy & Antihistamines',
                'manufacturer' => 'GlaxoSmithKline (GSK) / KPI',
                'base_unit' => 'Tablet',
                'description' => 'First-generation antihistamine for allergies, insect stings, and night-time itching.',
                'reorder_level' => 100,
                'requires_prescription' => false,
                'supplier_id' => $kpiSupplier->id ?? null,
                'batch_number' => 'PRT4-' . date('y') . '811',
                'mfg_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+35 months')),
                'purchase_price' => 50.00,
                'selling_price' => 100.00,
                'initial_stock' => 1000,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 1000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 1000, 'selling_price' => 85000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── GASTROINTESTINAL & DIGESTIVE HEALTH ────────────────────────────────────
            [
                'name' => 'Omeprazole 20mg Capsules (Omep)',
                'generic_name' => 'Omeprazole 20mg (Delayed Release)',
                'category_name' => 'Gastrointestinal & Digestive Health',
                'manufacturer' => 'Rene Industries Ltd / Cosmos',
                'base_unit' => 'Capsule',
                'description' => 'Proton pump inhibitor (PPI) for peptic ulcers, GERD, acid reflux, and gastritis.',
                'reorder_level' => 80,
                'requires_prescription' => false,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'OMP20-' . date('y') . '502',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+29 months')),
                'purchase_price' => 150.00,
                'selling_price' => 300.00,
                'initial_stock' => 800,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 3000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 27000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Esomeprazole 40mg Tablets (Nexium / Esomac)',
                'generic_name' => 'Esomeprazole Magnesium Trihydrate 40mg',
                'category_name' => 'Gastrointestinal & Digestive Health',
                'manufacturer' => 'Cipla QCIL / Surgipharm',
                'base_unit' => 'Tablet',
                'description' => 'High-potency PPI for severe erosive esophagitis and refractory gastric ulcers.',
                'reorder_level' => 30,
                'requires_prescription' => true,
                'supplier_id' => $ciplaSupplier->id ?? null,
                'batch_number' => 'ESM40-' . date('y') . '094',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+28 months')),
                'purchase_price' => 800.00,
                'selling_price' => 1500.00,
                'initial_stock' => 300,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 15000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 30, 'selling_price' => 42000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Oral Rehydration Salts (ORS) + Zinc Sulphate 20mg Kits',
                'generic_name' => 'WHO Low Osmolarity ORS Sachet 20.5g + Zinc 20mg',
                'category_name' => 'Gastrointestinal & Digestive Health',
                'manufacturer' => 'Cipla QCIL / JMS',
                'base_unit' => 'Sachet',
                'description' => 'Essential treatment kit for acute diarrhoea and cholera dehydration in children and adults.',
                'reorder_level' => 50,
                'requires_prescription' => false,
                'supplier_id' => $jmsSupplier->id ?? null,
                'batch_number' => 'ORSZ-' . date('y') . '330',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+32 months')),
                'purchase_price' => 700.00,
                'selling_price' => 1500.00,
                'initial_stock' => 250,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 50, 'selling_price' => 70000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Loperamide 2mg Capsules (Imodium)',
                'generic_name' => 'Loperamide Hydrochloride 2mg',
                'category_name' => 'Gastrointestinal & Digestive Health',
                'manufacturer' => 'Johnson & Johnson / Rene Industries',
                'base_unit' => 'Capsule',
                'description' => 'Antidiarrheal medication to reduce frequency of bowel movements in non-infectious diarrhoea.',
                'reorder_level' => 40,
                'requires_prescription' => false,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'LPR2-' . date('y') . '115',
                'mfg_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+31 months')),
                'purchase_price' => 200.00,
                'selling_price' => 400.00,
                'initial_stock' => 300,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 4000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 36000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Albendazole 400mg Chewable Tablets (Zentel)',
                'generic_name' => 'Albendazole 400mg',
                'category_name' => 'Antimalarials & Antiparasitics',
                'manufacturer' => 'GlaxoSmithKline (GSK) / KPI',
                'base_unit' => 'Tablet',
                'description' => 'Single-dose broad-spectrum deworming anthelmintic for roundworms, hookworms, and pinworms.',
                'reorder_level' => 50,
                'requires_prescription' => false,
                'supplier_id' => $kpiSupplier->id ?? null,
                'batch_number' => 'ALB400-' . date('y') . '810',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+33 months')),
                'purchase_price' => 600.00,
                'selling_price' => 1500.00,
                'initial_stock' => 200,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 135000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── CARDIOVASCULAR & ANTIHYPERTENSIVES ─────────────────────────────────────
            [
                'name' => 'Amlodipine 5mg Tablets',
                'generic_name' => 'Amlodipine Besylate 5mg',
                'category_name' => 'Cardiovascular & Antihypertensives',
                'manufacturer' => 'Cipla QCIL / Rene Industries',
                'base_unit' => 'Tablet',
                'description' => 'Calcium channel blocker for management of hypertension and chronic stable angina.',
                'reorder_level' => 60,
                'requires_prescription' => true,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'AML5-' . date('y') . '309',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+32 months')),
                'purchase_price' => 100.00,
                'selling_price' => 200.00,
                'initial_stock' => 600,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 2000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 18000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Losartan Potassium 50mg Tablets',
                'generic_name' => 'Losartan Potassium 50mg',
                'category_name' => 'Cardiovascular & Antihypertensives',
                'manufacturer' => 'Medisell / Torrent Pharmaceuticals',
                'base_unit' => 'Tablet',
                'description' => 'Angiotensin II receptor blocker (ARB) for treatment of high blood pressure and renal protection in diabetes.',
                'reorder_level' => 40,
                'requires_prescription' => true,
                'supplier_id' => $ciplaSupplier->id ?? null,
                'batch_number' => 'LST50-' . date('y') . '718',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+33 months')),
                'purchase_price' => 250.00,
                'selling_price' => 500.00,
                'initial_stock' => 400,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 5000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 46000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── DIABETES & ENDOCRINE CARE ──────────────────────────────────────────────
            [
                'name' => 'Metformin 500mg Tablets (Glucophage)',
                'generic_name' => 'Metformin Hydrochloride 500mg',
                'category_name' => 'Diabetes & Endocrine Care',
                'manufacturer' => 'Merck / Rene Industries',
                'base_unit' => 'Tablet',
                'description' => 'Biguanide first-line oral antidiabetic for type 2 diabetes mellitus glycemic control.',
                'reorder_level' => 80,
                'requires_prescription' => true,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'MTF500-' . date('y') . '401',
                'mfg_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+31 months')),
                'purchase_price' => 100.00,
                'selling_price' => 200.00,
                'initial_stock' => 800,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 2000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 18000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── DERMATOLOGY & TOPICALS ─────────────────────────────────────────────────
            [
                'name' => 'Funbact A Triple Action Cream (30g)',
                'generic_name' => 'Clotrimazole 1% + Betamethasone 0.05% + Neomycin 0.5%',
                'category_name' => 'Dermatology & Skin Care',
                'manufacturer' => 'Shalina Healthcare / AstraPharma',
                'base_unit' => 'Tube',
                'description' => 'High-demand triple-action antibacterial, antifungal, and anti-inflammatory topical cream.',
                'reorder_level' => 30,
                'requires_prescription' => false,
                'supplier_id' => $astraSupplier->id ?? null,
                'batch_number' => 'FNB30-' . date('y') . '880',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+27 months')),
                'purchase_price' => 3800.00,
                'selling_price' => 6000.00,
                'initial_stock' => 100,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 10, 'selling_price' => 57000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Clotrimazole 1% Topical Cream (Canesten 20g)',
                'generic_name' => 'Clotrimazole 1% w/w',
                'category_name' => 'Antifungals & Antimycotics',
                'manufacturer' => 'Bayer / Rene Industries',
                'base_unit' => 'Tube',
                'description' => 'Broad-spectrum topical antifungal for athlete\'s foot, ringworm, candidiasis, and jock itch.',
                'reorder_level' => 20,
                'requires_prescription' => false,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'CLT20-' . date('y') . '221',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+26 months')),
                'purchase_price' => 2500.00,
                'selling_price' => 4500.00,
                'initial_stock' => 80,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 10, 'selling_price' => 42000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── OPHTHALMIC & ENT CARE ──────────────────────────────────────────────────
            [
                'name' => 'Chloramphenicol 0.5% Eye Drops (10ml)',
                'generic_name' => 'Chloramphenicol 0.5% w/v',
                'category_name' => 'Ophthalmic & ENT Care',
                'manufacturer' => 'Abacus Parenteral Drugs (APDL)',
                'base_unit' => 'Bottle',
                'description' => 'Broad-spectrum antibacterial ophthalmic solution for bacterial conjunctivitis ("red eye").',
                'reorder_level' => 25,
                'requires_prescription' => false,
                'supplier_id' => $abacusSupplier->id ?? null,
                'batch_number' => 'CHL10-' . date('y') . '009',
                'mfg_date' => date('Y-m-d', strtotime('-2 months')),
                'expiry_date' => date('Y-m-d', strtotime('+22 months')),
                'purchase_price' => 2000.00,
                'selling_price' => 3500.00,
                'initial_stock' => 75,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 20, 'selling_price' => 65000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── VITAMINS & MATERNAL HEALTH ─────────────────────────────────────────────
            [
                'name' => 'FEFO Tablets (Ferrous Sulphate 200mg + Folic Acid 0.4mg)',
                'generic_name' => 'Dried Ferrous Sulphate 200mg + Folic Acid 400mcg',
                'category_name' => 'Vitamins, Minerals & Supplements',
                'manufacturer' => 'Kampala Pharmaceutical Industries (KPI)',
                'base_unit' => 'Tablet',
                'description' => 'Standard antenatal care hematinic for prophylaxis and treatment of iron deficiency anaemia.',
                'reorder_level' => 100,
                'requires_prescription' => false,
                'supplier_id' => $kpiSupplier->id ?? null,
                'batch_number' => 'FEFO-' . date('y') . '991',
                'mfg_date' => date('Y-m-d', strtotime('-4 months')),
                'expiry_date' => date('Y-m-d', strtotime('+32 months')),
                'purchase_price' => 50.00,
                'selling_price' => 100.00,
                'initial_stock' => 1500,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 1000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 1000, 'selling_price' => 85000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Vitamin C 100mg Chewable Tablets (Orange Flavour)',
                'generic_name' => 'Ascorbic Acid 100mg',
                'category_name' => 'Vitamins, Minerals & Supplements',
                'manufacturer' => 'Rene Industries Ltd',
                'base_unit' => 'Tablet',
                'description' => 'Daily immune system booster and antioxidant for cold recovery and tissue repair.',
                'reorder_level' => 100,
                'requires_prescription' => false,
                'supplier_id' => $reneSupplier->id ?? null,
                'batch_number' => 'VTC100-' . date('y') . '601',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+33 months')),
                'purchase_price' => 50.00,
                'selling_price' => 100.00,
                'initial_stock' => 1200,
                'units' => [
                    ['unit_name' => 'Strip', 'conversion_factor' => 10, 'selling_price' => 1000.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 1000, 'selling_price' => 80000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],

            // ── FIRST AID, SURGICAL & MEDICAL SUPPLIES ─────────────────────────────────
            [
                'name' => 'Examination Latex Gloves (Box of 100)',
                'generic_name' => 'Non-Sterile Disposable Examination Gloves Medium',
                'category_name' => 'First Aid, Surgical & Medical Supplies',
                'manufacturer' => 'Top Glove / JMS',
                'base_unit' => 'Piece',
                'description' => 'High-elasticity ambidextrous examination gloves for clinical and dispensary protection.',
                'reorder_level' => 100,
                'requires_prescription' => false,
                'supplier_id' => $jmsSupplier->id ?? null,
                'batch_number' => 'GLV100-' . date('y') . '502',
                'mfg_date' => date('Y-m-d', strtotime('-5 months')),
                'expiry_date' => date('Y-m-d', strtotime('+40 months')),
                'purchase_price' => 180.00,
                'selling_price' => 300.00,
                'initial_stock' => 500,
                'units' => [
                    ['unit_name' => 'Pair', 'conversion_factor' => 2, 'selling_price' => 600.00, 'is_default_sale' => true, 'is_default_purchase' => false],
                    ['unit_name' => 'Box', 'conversion_factor' => 100, 'selling_price' => 25000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
            [
                'name' => 'Surgical Spirit 70% (500ml)',
                'generic_name' => 'Denatured Ethyl Alcohol 70% v/v Antiseptic',
                'category_name' => 'First Aid, Surgical & Medical Supplies',
                'manufacturer' => 'Sarjan Healthcare / JMS',
                'base_unit' => 'Bottle',
                'description' => 'Skin antiseptic and disinfectant for skin preparation prior to injection and wound cleansing.',
                'reorder_level' => 15,
                'requires_prescription' => false,
                'supplier_id' => $jmsSupplier->id ?? null,
                'batch_number' => 'SPT500-' . date('y') . '311',
                'mfg_date' => date('Y-m-d', strtotime('-3 months')),
                'expiry_date' => date('Y-m-d', strtotime('+33 months')),
                'purchase_price' => 4500.00,
                'selling_price' => 7000.00,
                'initial_stock' => 40,
                'units' => [
                    ['unit_name' => 'Box', 'conversion_factor' => 12, 'selling_price' => 78000.00, 'is_default_sale' => false, 'is_default_purchase' => true],
                ],
            ],
        ];

        foreach ($medicinesData as $item) {
            $cat = $categories->get($item['category_name']);
            if (!$cat) {
                // Fallback to first category if not matched by name
                $cat = Category::where('name', 'like', '%' . explode(' ', $item['category_name'])[0] . '%')->first()
                    ?? Category::first();
            }

            $medicine = Medicine::firstOrCreate(
                ['name' => $item['name']],
                [
                    'generic_name' => $item['generic_name'],
                    'category_id' => $cat->id ?? 1,
                    'manufacturer' => $item['manufacturer'],
                    'base_unit' => $item['base_unit'],
                    'description' => $item['description'],
                    'reorder_level' => $item['reorder_level'],
                    'requires_prescription' => $item['requires_prescription'],
                    'is_active' => true,
                ]
            );

            // Seed units (including Box, Strip, Bottle, Sachet, etc.)
            foreach ($item['units'] as $unit) {
                MedicineUnit::firstOrCreate(
                    [
                        'medicine_id' => $medicine->id,
                        'unit_name' => $unit['unit_name'],
                    ],
                    [
                        'conversion_factor' => $unit['conversion_factor'],
                        'selling_price' => $unit['selling_price'],
                        'is_default_sale' => $unit['is_default_sale'] ?? false,
                        'is_default_purchase' => $unit['is_default_purchase'] ?? false,
                    ]
                );
            }

            // Seed active stock batch
            Batch::firstOrCreate(
                [
                    'medicine_id' => $medicine->id,
                    'batch_number' => $item['batch_number'],
                ],
                [
                    'supplier_id' => $item['supplier_id'],
                    'mfg_date' => $item['mfg_date'],
                    'expiry_date' => $item['expiry_date'],
                    'purchase_price' => $item['purchase_price'],
                    'selling_price' => $item['selling_price'],
                    'quantity' => $item['initial_stock'],
                    'is_active' => true,
                ]
            );
        }
    }
}
