<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Pre-configured Essential Medicine Templates
    |--------------------------------------------------------------------------
    | These templates speed up the entry of medicines into the system while
    | allowing the user to override, edit, or customize any field.
    */
    'templates' => [
        [
            'name' => 'Paracetamol 500mg Tablets',
            'generic_name' => 'Paracetamol',
            'category_slug' => 'painkillers-analgesics',
            'manufacturer' => 'Abacus Pharma',
            'base_unit' => 'Tablet',
            'description' => 'Fast-acting pain and fever relief for mild to moderate pain, headaches, and toothache.',
            'reorder_level' => 100,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Amoxicillin 500mg Capsules',
            'generic_name' => 'Amoxicillin Trihydrate',
            'category_slug' => 'antibiotics-antimicrobials',
            'manufacturer' => 'Cipla Quality Chemical',
            'base_unit' => 'Capsule',
            'description' => 'Broad-spectrum antibiotic for bacterial infections (respiratory, ear, urinary tract, and dental).',
            'reorder_level' => 50,
            'requires_prescription' => true,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Artemether / Lumefantrine 20/120mg (Coartem)',
            'generic_name' => 'Artemether + Lumefantrine',
            'category_slug' => 'antimalarials-antiparasitics',
            'manufacturer' => 'Novartis / Cipla',
            'base_unit' => 'Tablet',
            'description' => 'First-line ACT combination therapy for acute uncomplicated Plasmodium falciparum malaria.',
            'reorder_level' => 30,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Pack (6x4)', 'conversion_factor' => 24],
                ['unit_name' => 'Box (30 Packs)', 'conversion_factor' => 720],
            ],
        ],
        [
            'name' => 'Omeprazole 20mg Delayed-Release Capsules',
            'generic_name' => 'Omeprazole',
            'category_slug' => 'gastrointestinal-digestive',
            'manufacturer' => 'Cosmos Pharmaceuticals',
            'base_unit' => 'Capsule',
            'description' => 'Proton pump inhibitor (PPI) for peptic ulcers, heartburn, gastritis, and GERD acid reflux.',
            'reorder_level' => 40,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box (3 Strips)', 'conversion_factor' => 30],
                ['unit_name' => 'Box (10 Strips)', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Cetirizine Hydrochloride 10mg Tablets',
            'generic_name' => 'Cetirizine HCl',
            'category_slug' => 'allergy-antihistamines',
            'manufacturer' => 'Dawa Limited',
            'base_unit' => 'Tablet',
            'description' => 'Non-drowsy 24-hour antihistamine for allergic rhinitis, hay fever, skin allergy, and urticaria.',
            'reorder_level' => 50,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Metformin Hydrochloride 500mg Tablets',
            'generic_name' => 'Metformin HCl',
            'category_slug' => 'diabetes-endocrine',
            'manufacturer' => 'Medreich Pharma',
            'base_unit' => 'Tablet',
            'description' => 'Biguanide oral antidiabetic medication for glycemic control in Type 2 Diabetes.',
            'reorder_level' => 50,
            'requires_prescription' => true,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Amlodipine Besylate 5mg Tablets',
            'generic_name' => 'Amlodipine',
            'category_slug' => 'cardiovascular-antihypertensives',
            'manufacturer' => 'Pfizer / Generic Pharma',
            'base_unit' => 'Tablet',
            'description' => 'Calcium channel blocker for hypertension management and chronic stable angina.',
            'reorder_level' => 40,
            'requires_prescription' => true,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Ciprofloxacin 500mg Film-Coated Tablets',
            'generic_name' => 'Ciprofloxacin HCl',
            'category_slug' => 'antibiotics-antimicrobials',
            'manufacturer' => 'Bayer / Abacus Pharma',
            'base_unit' => 'Tablet',
            'description' => 'Fluoroquinolone antibacterial agent for complicated UTIs, typhoid, and enteric infections.',
            'reorder_level' => 30,
            'requires_prescription' => true,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Ibuprofen 400mg Film-Coated Tablets',
            'generic_name' => 'Ibuprofen',
            'category_slug' => 'painkillers-analgesics',
            'manufacturer' => 'Macleods Pharma',
            'base_unit' => 'Tablet',
            'description' => 'Non-steroidal anti-inflammatory drug (NSAID) for muscle pain, backache, arthritis, and fever.',
            'reorder_level' => 50,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Strip', 'conversion_factor' => 10],
                ['unit_name' => 'Box', 'conversion_factor' => 100],
            ],
        ],
        [
            'name' => 'Oral Rehydration Salts (ORS) Low-Osmolarity Sachet',
            'generic_name' => 'ORS (Sodium Chloride, Glucose, Potassium, Citrate)',
            'category_slug' => 'gastrointestinal-digestive',
            'manufacturer' => 'JMS / NMS',
            'base_unit' => 'Sachet',
            'description' => 'Electrolyte replacement sachet for treating acute dehydration caused by diarrhea and vomiting.',
            'reorder_level' => 60,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Pack', 'conversion_factor' => 10],
                ['unit_name' => 'Box (50 Sachets)', 'conversion_factor' => 50],
            ],
        ],
        [
            'name' => 'Multivitamin & Minerals Tonic Syrup 100ml',
            'generic_name' => 'Multivitamin + Zinc + Iron Syrup',
            'category_slug' => 'vitamins-supplements',
            'manufacturer' => 'Universal Pharmacy',
            'base_unit' => 'Bottle',
            'description' => 'Nutritional supplement syrup for immune boost, appetite stimulation, and daily vitamin support.',
            'reorder_level' => 20,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Box (12 Bottles)', 'conversion_factor' => 12],
                ['unit_name' => 'Carton (48 Bottles)', 'conversion_factor' => 48],
            ],
        ],
        [
            'name' => 'Diclofenac Sodium 1% Topical Pain Gel 30g',
            'generic_name' => 'Diclofenac Diethylamine Gel',
            'category_slug' => 'musculoskeletal-joint-care',
            'manufacturer' => 'Novartis / GSK',
            'base_unit' => 'Tube',
            'description' => 'Targeted anti-inflammatory pain relief gel for sprains, sports injuries, and joint stiffness.',
            'reorder_level' => 25,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Box (10 Tubes)', 'conversion_factor' => 10],
            ],
        ],
        [
            'name' => 'Clotrimazole 1% Topical Antifungal Cream 20g',
            'generic_name' => 'Clotrimazole',
            'category_slug' => 'antifungals-antimycotics',
            'manufacturer' => 'Bayer / Cipla',
            'base_unit' => 'Tube',
            'description' => 'Broad-spectrum topical antifungal cream for ringworm, athlete\'s foot, and skin candidiasis.',
            'reorder_level' => 25,
            'requires_prescription' => false,
            'units' => [
                ['unit_name' => 'Box (10 Tubes)', 'conversion_factor' => 10],
            ],
        ],
        [
            'name' => 'Salbutamol Inhaler 100mcg (200 Doses)',
            'generic_name' => 'Salbutamol Sulfate',
            'category_slug' => 'cough-cold-respiratory',
            'manufacturer' => 'GSK (GlaxoSmithKline)',
            'base_unit' => 'Piece',
            'description' => 'Fast-acting bronchodilator rescue inhaler for asthma, bronchospasm, and COPD relief.',
            'reorder_level' => 15,
            'requires_prescription' => true,
            'units' => [
                ['unit_name' => 'Box (10 Inhalers)', 'conversion_factor' => 10],
            ],
        ],
        [
            'name' => 'Gentamicin 0.3% Sterile Eye/Ear Drops 10ml',
            'generic_name' => 'Gentamicin Sulfate',
            'category_slug' => 'ophthalmic-ent-care',
            'manufacturer' => 'Abacus Pharma',
            'base_unit' => 'Bottle',
            'description' => 'Antibacterial ophthalmic and otic drops for conjunctivitis and external ear canal infections.',
            'reorder_level' => 20,
            'requires_prescription' => true,
            'units' => [
                ['unit_name' => 'Box (12 Bottles)', 'conversion_factor' => 12],
            ],
        ],
    ],
];
